# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-15 05:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('tag', models.CharField(max_length=1000)),
                ('text', models.TextField(null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('isShared', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='noteBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('tag', models.CharField(max_length=1000)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('isShared', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='note',
            name='notebook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LNote.noteBook'),
        ),
    ]
