# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-15 07:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('LNote', '0002_auto_20171115_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='sharedWith',
            field=models.ManyToManyField(default=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
