# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-21 08:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LNote', '0008_auto_20171121_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='sharedWith',
        ),
    ]
