# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-21 08:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LNote', '0009_remove_note_sharedwith'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notebook',
            name='sharedWith',
        ),
    ]
