# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-21 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LNote', '0010_remove_notebook_sharedwith'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharednote',
            name='sharedById',
            field=models.IntegerField(default=True),
        ),
        migrations.AlterField(
            model_name='sharednote',
            name='sharedWithId',
            field=models.IntegerField(default=True),
        ),
    ]
