# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-21 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LNote', '0011_auto_20171121_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharednote',
            name='sharedById',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sharednote',
            name='sharedByName',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='sharednote',
            name='sharedWithId',
            field=models.IntegerField(),
        ),
    ]
