# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-21 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LNote', '0012_auto_20171121_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharednote',
            name='text',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='sharednote',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default='2017-11-21T13:42:09.539000Z'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sharednote',
            name='title',
            field=models.CharField(default='demo', max_length=128),
            preserve_default=False,
        ),
    ]
